version: "3.9"

services:
  app:
    build: .
    container_name: ftodo-rest-server
    ports:
      - "3000:3000"
    depends_on:
      - postgresdb
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_TOKEN_PREFIX: ${JWT_TOKEN_PREFIX}

  postgresdb:
    image: postgres:alpine
    container_name: ftodo-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ftodo_data:/var/lib/postgresql/data

volumes:
  ftodo_data:
